apiVersion: apps/v1
kind: Deployment
metadata:
  name: smsrs-reservation-backend
  namespace: backend
  labels:
    app: smsrs-reservation-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: smsrs-reservation-backend
  template:
    metadata:
      labels:
        app: smsrs-reservation-backend
    spec:
      containers:
      - name: smsrs-reservation-backend
        image: khantki/smsrs-reservation-backend-service:linux
        ports:
        - containerPort: 3100
        resources:
          requests:
            cpu: "250m"   # Requests 250 milliCPU
            memory: "512Mi"  # Requests 512 MiB of memory
          limits:
            cpu: "500m"   # Limits to 500 milliCPU
            memory: "1Gi"  # Limits to 1 GiB of memory
---
apiVersion: v1
kind: Service
metadata:
  name: smsrs-reservation-backend
  namespace: backend
spec:
  selector:
    app: smsrs-reservation-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3100
  type: ClusterIP  
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: smsrs-reservation-backend
spec:
  maxReplicas: 6
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: smsrs-reservation-backend
  targetCPUUtilizationPercentage: 75
status:
  currentReplicas: 0
  desiredReplicas: 0