apiVersion: apps/v1
kind: Deployment
metadata:
  name: smsrs-frontend
  namespace: frontend  # Ensure this matches the namespace of your ConfigMap
  labels:
    app: smsrs-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: smsrs-frontend
  template:
    metadata:
      labels:
        app: smsrs-frontend
    spec:
      containers:
      - name: frontend-container
        image: khantki/smsrs-frontend:linux
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: my-config
---
apiVersion: v1
kind: Service
metadata:
  name: smsrs-frontend
  namespace: frontend
spec:
  selector:
    app: smsrs-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # Ensure targetPort matches containerPort
  type: LoadBalancer  # Expose service externally, if needed