apiVersion: apps/v1
kind: Deployment
metadata:
  name: smsrs-frontend
  namespace: frontend
  labels:
    app: smsrs-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: smsrs-frontend
  template:
    metadata:
      labels:
        app: smsrs-frontend
    spec:
      containers:
      - name: frontend-container  # Added name field for the container
        image: khantki/smsrs-frontend:linux  # Ensure the correct image tag
        ports:
        - containerPort: 80
        env:
        - name: RESERVATION_API
          value: http://smsrs-reservation-backend.backend.svc.cluster.local  # Correct DNS format
---
apiVersion: v1
kind: Service
metadata:
  name: smsrs-frontend
  namespace: frontend
spec:
  selector:
    app: smsrs-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # Ensure targetPort matches containerPort
  type: LoadBalancer  # Expose service externally, if needed