apiVersion: apps/v1
kind: Deployment
metadata:
  name: smsrs-frontend
  namespace: frontend
  labels:
    app: smsrs-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: smsrs-frontend
  template:
    metadata:
      labels:
        app: smsrs-frontend
    spec:
      containers:
      - name: frontend-container
        image: khantki/smsrs-frontend:linux
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: my-config
        resources:
          requests:
            cpu: "250m"   # Requests 250 milliCPU
            memory: "512Mi"  # Requests 512 MiB of memory
          limits:
            cpu: "500m"   # Limits to 500 milliCPU
            memory: "1Gi"  # Limits to 1 GiB of memory
---
apiVersion: v1
kind: Service
metadata:
  name: smsrs-frontend
  namespace: frontend
spec:
  selector:
    app: smsrs-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # Ensure targetPort matches containerPort
  type: LoadBalancer  # Expose service externally, if needed
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: smsrs-frontend-hpa
  namespace: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: smsrs-frontend
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
